# Generated by Django 4.0.3 on 2022-04-04 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project_prep.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('Dress', 'Dress'), ('Trousers', 'Trousers'), ('Skirt', 'Skirt'), ('Shirt', 'Shirt'), ('Coat', 'Coat'), ('Cardigans', 'Cardigans'), ('Other', 'Other')], max_length=9)),
                ('materials', models.CharField(choices=[('linen', 'linen'), ('Cotton', 'Cotton'), ('Linnen/Cotton', 'Linnen/Cotton'), ('Silk', 'Silk'), ('Wool', 'Wool')], max_length=13)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OwnedGarment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3)),
                ('garment_owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('garment_size', models.ManyToManyField(to='main.garment')),
            ],
        ),
        migrations.CreateModel(
            name='GarmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', validators=[project_prep.common.validators.MaxFileSizeInMbValidator(5)])),
                ('description', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('tagged_garments', models.ManyToManyField(to='main.ownedgarment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
