# Generated by Django 4.0.3 on 2022-04-05 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_ownedgarment_garment_owner_ownedgarment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownedgarment',
            old_name='user',
            new_name='garment_owner',
        ),
    ]
