# Generated by Django 4.0.3 on 2022-04-06 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_user_ownedgarment_garment_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownedgarment',
            name='garment',
        ),
        migrations.AddField(
            model_name='ownedgarment',
            name='garment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.garment'),
        ),
    ]
