# Generated by Django 4.0.3 on 2022-04-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_ownedgarment_garment_ownedgarment_garment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedgarment',
            name='own_name',
            field=models.CharField(default='shirt', max_length=30),
            preserve_default=False,
        ),
    ]
