# Generated by Django 4.0.3 on 2022-04-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_ownedgarment_own_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedgarment',
            name='own_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
