# Generated by Django 4.0.3 on 2022-04-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_ownedgarment_own_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
