# Generated by Django 4.0.3 on 2022-04-14 13:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_garment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='garmentphoto',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
